exec_queryset/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orm.urls', namespace='orm')),
] + static(settings.STATIC_URL) 

orm/urls.py
from django.urls import path

from orm import views

app_name = 'orm'

urlpatterns = [
    path('', views.main, name='main'),
    path('clear/', views.clear, name='clear'),
    path('<int:id>/', views.main, name='task')
]

orm/models/models.py
from django.db import models
from django.urls import reverse


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

class Book(models.Model):
    author = models.ManyToManyField(Author, related_name='books')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='books')
    name = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name

class BookP(Book):
    class Meta:
        proxy = True

    def __str__(self):
        return self.name


TASK_LEVELS = [
    ('easy', 'Easy'),
    ('medium', 'Medium'),
    ('hard', 'Hard'),
 ]
SPECIAL_TASKS = [
    ('create', 'Create'),
    ('delete', 'Delete'),
    ('none', 'None'),
    ('random', 'Random'),
    ('update', 'Update'),
]

class Task(models.Model):
    title = models.CharField(max_length=1000)
    level = models.CharField(max_length=10, choices=TASK_LEVELS)
    special_task = models.CharField(max_length=10, choices=SPECIAL_TASKS, default='none')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('orm:task', args=[self.pk])


class Result(models.Model):
    code = models.CharField(max_length=200)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='result')

    def __str__(self):
        return self.code
    

orm/models/tasks.py
from django.db.models import Q

from .models import Task


TASK_LEVELS = ['easy', 'medium', 'hard']

# The function retrieves tasks they aren't yet completed 
def get_context_tasks(id, session):
        idx_list_session = session.task['list']
        context = {'current_task': None}
        context['tasks'] = sorted_tasks()

        # iterates through task levels and retrieves objects from database they aren't completed
        for task_level in TASK_LEVELS:
            task_objects = Task.objects.filter(Q(level=task_level))
            context[task_level] = task_objects
        
        # when request refers to specific task. It retrieves from database and
        # returns all tasks and specific task if there is request
        if id:
            try:
                current_task = Task.objects.get(id=id)
            except Task.DoesNotExist:
                return optional_task(context, idx_list_session)

            context['current_task'] = current_task
            return context
        else:
            return optional_task(context, idx_list_session)
            

# The function gets any task to display in main site if any are
def optional_task(context, session):
    for task in context['tasks']:
        if task.id not in session:     
            context['current_task'] = task
            return context
    context['current_task'] = context['tasks'][0]
    return context


def sorted_tasks():
    tasks = Task.objects.all()
    order = { key: i for i, key in enumerate(TASK_LEVELS)}
    tasks = sorted(tasks, key=lambda t: order[t.level])
    return tasks

orm/models/validator.py
import logging
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Length

from .models import Book, Author, Category


logger = logging.getLogger(__name__)


class CheckCode(object):
    FORBIDDEN_METHODS = {
        'create': '.create(',
        'update': '.update(',
        'delete': '.delete(',
    }
    VALIDATE_NAMES = {
        'model': ['Book', 'Author', 'Category'],
        'manager': ['.objects', '.book', '.book_set'],
    }
    
    def __init__(self, request, context):
        self.correct_code = context['current_task'].result.first().code
        self.correct_objects = None
        self.request = request
        self.special_task = context['current_task'].special_task
        self.user_code = request.POST.get('code')
        self.user_objects = None

        if self.special_task == 'none':
            self.special_task = None
        else:
            self.correct_code = context['current_task'].result.all()
    
    def check(self):
        if not self.validate_name():
            return False
        
        if self.special_task:
            return self.special()

        if not self.forbidden_methods():
            return False

        if not self.queryset():
            return False
        try: 
            return self.user_objects == self.correct_objects
        except:
            messages.info(self.request, 'Invalid code')
            return False
    
    def validate_name(self):
        for key, value in self.VALIDATE_NAMES.items():
            aux = True
            for name in value:
                if name in self.user_code:
                    aux = False
                    break
            if aux:
                messages.info(self.request, f'Incorrect {key}')
                return False
        return True
    
    def forbidden_methods(self):
        # checks the code which not modify the database.
        for key, value in self.FORBIDDEN_METHODS.items():
            if value in self.user_code:
                messages.info(self.request, f'In this task we don\'t need to {key}')
                return False
        return True
    
    def queryset(self):
        try:
            self.user_objects = eval(self.user_code).query.__str__()
        except:
            try:
                self.user_objects = eval(self.user_code)
            except:
                messages.info(self.request, 'Incorrect syntax')
                return False

        try:
            self.correct_objects = eval(self.correct_code).query.__str__()
        except:
            try:
                self.correct_objects = eval(self.correct_code)
            except:
                messages.info(self.request, 'Program error, we apologize for the inconvenience :(')
                return False
        return True
    
    def special(self):
        if self.special_task == 'random':
            for correct in self.correct_code:
                if correct.code == self.format_user_code():
                    return True
        return False
    
    def format_user_code(self):
        return self.user_code.replace('\'', '\"')

orm/forms.py
from django import forms

class CodeForm(forms.Form):
    code = forms.CharField(max_length=300, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'autocomplete': 'off',
        }
    ))

orm/views.py
import logging
from django.shortcuts import redirect, render

from .forms import CodeForm
from .models import tasks, validator
from .tasks import SessionTask


logger = logging.getLogger(__name__)


def main(request, id=None):
    session = SessionTask(request)
    context = tasks.get_context_tasks(id, session)
    context['success_info'] = None 
    context['current_session_task'] = session.get_task(context['current_task'])
    context['session'] = session
    
    if request.method == 'POST':
        user_code = request.POST.get('code')
        print(user_code)
        context['form'] = CodeForm(request.POST)
        context['success_info'] = validator.CheckCode(request, context).check()
        context['current_session_task']['state'] = context['success_info']
        session.add(context, user_code)
        
    else:
        if context['current_session_task']:
            context['form'] = CodeForm(initial={'code': context['current_session_task']['code']})
        else:
            context['form'] = CodeForm()
    return render(request, 'apps/orm/main.html', context)


def clear(request):
    session = SessionTask(request)
    session.clear()
    return redirect('orm:main')

 

templates/apps/orm/main.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="content" id="main">
        <div id="task_number_list">
            <div class="display_f">          
                {% for task in tasks %}
                    <div>
                        <a href="{{ task.get_absolute_url }}">
                            {% if task.id in session.task.list %}
                                <div class="number_task  {{ task.level }}_tasks_color a_black">{{ forloop.counter }}</div>
                            {% else %}
                                <div class="number_task {{ task.level }}_tasks_color_opacity a_black">{{ forloop.counter }}</div>
                            {% endif %}
                        </a>
                        {{ current_session_task.id }}
                        {% if task.id == current_task.id %}
                            <div id="indicator"></div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="background_white padding_05 box_shadow_gray" id="functional_box">
            <div class="text_a_c padding_05">
                <h5>{{ current_task.title }}</h5>
            </div>
            <form action="{% url 'orm:task' current_task.id %}" method="POST">
                {% csrf_token %}
                <div class="input-group input-group-lg">
                    <span class="input-group-text" id="inputGroup-sizing-lg">Code</span> 
                    {{ form.code }}
                    {% comment %} <input type="text" class="form-control" name="code" autocomplete="off" value={% if current_session_task %}{{ current_session_task.code }}{% endif %}> {% endcomment %}
                </div>
            </form>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="success">
                {% if current_session_task.state %}
                    <img class="icon_check" src="{% static 'img/ok.png' %}">
                {% elif success_info %}
                    <img class="icon_check" id="icon_success" src="{% static 'img/ok.png' %}">
                {% elif success_info == False %}
                    <img class="icon_check" id="icon_failure" src="{% static 'img/error.png' %}">
                {% endif %}
            </div>        
            
            <div class="buttons_line">
                <button onclick="solution()" id="solution_button" class="button btn-warning width_30">Solution</button>
                <a href="{% url 'orm:main' %}"><button class="button btn-primary width_30">Next</button></a>
            </div>
            <div id="solution" class="display_none">
                <hr>
                {% for solution in current_task.result.all %}
                    <h5>{{ solution.code }}</h5>
                {% endfor %}
            </div>
        </div>
        <div class="background_white box_shadow_gray" id="list_tasks">
            <div class="group_tasks">
                <div class="level_box easy_tasks_color">
                    <p class="padding_05 margin_0">Easy level</p>
                </div>
                <div class="tasks">
                    {% for task in easy %}
                        <a href={{ task.get_absolute_url }}>
                            <div class="task">
                                <p>{{ task.title|truncatechars:30 }}</p>
                                {% if task.id in session.task.list %}
                                    <img class="icon_okk" src="{% static 'img/okk.png' %}">
                                {% else %}
                                    <div></div>
                                {% endif %}
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
           
            <div class="group_tasks">
                <div class="level_box medium_tasks_color">
                    <p class="padding_05 margin_0">Medium level</p>
                </div>
                <div class="tasks">
                    {% for task in medium %}
                        <a href={{ task.get_absolute_url }}>
                            <div class="task">
                                <p>{{ task.title|truncatechars:30 }}</p>
                                {% if task.id in session.task.list %}
                                    <img class="icon_okk" src="{% static 'img/okk.png' %}">
                                {% else %}
                                    <div></div>
                                {% endif %}
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="group_tasks">
                <div  class="level_box hard_tasks_color">
                    <p class="padding_05 margin_0">Hard level</p>
                </div>
                <div class="tasks">
                    {% for task in hard %}
                        <a href={{ task.get_absolute_url }}>
                            <div class="task">
                                <p>{{ task.title|truncatechars:30 }}</p>
                                {% if task.id in session.task.list %}
                                    <img class="icon_okk" src="{% static 'img/okk.png' %}">
                                {% endif %}
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div id="image_models">
            <img class="width_100" src="{% static 'img/models.jpg' %}">
        </div>
    </div>
    
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>ORM</title>
</head>
<body class="margin_0 background_gray">
    <div id="main_bar">
        <div id="imain">
            <h1>ORM</h1>
            <h3 class="color_white"><a class="a_white" href="{% url 'orm:clear' %}">Clear</a></h3>
        </div>
    </div>
    {% block content %}{% endblock content %}
</body>
</html>